AppBundle\Entity\Deposit:
    type: entity
    table: deposit
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: NONE
    fields:
        amount:
            type: float

    manyToOne:
        expense:
            targetEntity: AppBundle\Entity\Expense
            inversedBy: deposits
            joinColumn:
                name: expense_id
                referencedColumnName: id
