AppBundle\Entity\Expense:
    type: entity
    table: expense
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 255
        amount:
            type: float
        createdAt:
            type: datetime
            options:
                 default: 0
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            options:
                 default: 0
            gedmo:
                timestampable:
                    on: update

    oneToMany:
        deposits:
            targetEntity: AppBundle\Entity\Deposit
            mappedBy: expense
            cascade: [ all ]
            fetch: EAGER
